image: registry.backpackcloud.com/backpackcloud/maven

stages:
  - build
  - release

mvn:package:
  stage: build
  artifacts:
    paths:
      - target/fakeomatic-runner
  script:
    - build native

release:downstream:
  stage: release
  dependencies:
    - mvn:package
  script:
    - upload target/fakeomatic-runner fakeomatic