= Fake-O-Matic

Fake-O-Matic is a utility tool for creating and sending fake payloads to endpoints in order to test throughput.
On each iteration, Fake-O-Matic will generate a payload based on a provided template and a set of rules for generating
fake data.

== How to Build

Fake-O-Matic is build with https://quarkus.io[Quarkus] and supports native compilation. THe build is a good and old
`mvn package` command. If you wish to build a native binary, just activate the `native` profile
(`mvn -P native package`).

It's also possible to build Fake-O-Matic using https://github.com/openshift/source-to-image[source-to-image]:

[source,shell script]
----
s2i build . quay.io/quarkus/ubi-quarkus-native-s2i:19.3.2-java11 backpackcloud/fakeomatic
----

Fake-O-Matic is also published at https://quay.io/backpackcloud/fakeomatic[Quay.io]

== How to Configure

Fake-O-Matic expects you to define both data and template to generate the payloads. An optional seed can also be given
for reproducibility.

=== Data Generation

The rules for generating data can contain `samples` and `placeholders`. Samples are a set of data that Fake-O-Matic can
randomly pick and placeholders are characters that can be associated with the samples for to allow the use of
expressions for generating data.

==== Samples

Samples might have 3 different types:

chars::
This sample can pick any character from a given string. Useful for defining a set of characters that can be used to
produce IDs or any other information that is not meant to be read. It takes a String param `values` for configuring
the chars.

[source,yaml]
----
samples:
  letter:
    type: chars
    value: "abcdefghijklmnopqrstuvwxyz"
  digit:
    type: chars
    value: "0123456789"
----

list::
This sample can pick any item from a given list of objects. The object will be used in its `string` form. Useful for
defining a set of data that is meant to be read, like cities and names. It takes an Array param `values`
configuring the items.

[source,yaml]
----
samples:
  cause:
    type: list
    values:
      - "clock speed"
      - "solar flares"
      - "electromagnetic radiation from satellite debris"
      - "static from nylon underwear"
      - "static from plastic slide rules"
      - "global warming"
      - "poor power conditioning"
      - "static buildup"
      - "doppler effect"
----

api::
This sample actually calls a given API to get data to use every time it's asked for a data. It takes a URL param
`url` to define the API endpoint and a https://tools.ietf.org/html/rfc6901[JSON Pointer] param `result` to specify
which part of the API response represents the data. Due to the nature of this sample, it's not possible to reproduce the
same payloads without relying on the dependent API.

[source,yaml]
----
samples:
  chuck_norris:
    type: api
    url: https://api.chucknorris.io/jokes/random
    result: /value
----

uuid::
This sample will produce a https://en.wikipedia.org/wiki/Universally_unique_identifier[universally unique identifier].
It doesn't take any specific param.

[source,yaml]
----
samples:
  uuid:
    type: uuid
----

composite::
This sample will gather other samples and join them into a unique data. It takes an Array param `samples` to specify
the samples to gather and an optional String param `separator` to specify the separator (defaults to `" "`).

[source,yaml]
----
samples:
  name:
    type: composite
    samples:
      - first_name
      - last_name
----

weight::
This sample allows you to define weights to each list item. It takes an Array param `values` with a `weight` and a
`value` field.
[source,yaml]
----
samples:
  color:
    type: weight
    values:
      - weight: 30
        value: blue
      - weight: 45
        value: yellow
      - weight: 10
        value: red
      - weight: 20
        value: brown
      - weight: 25
        value: cyan
----

Notice that the sum of the weights don't necessary need to be `100`, but using a total weight of `100` helps to see the
weights as percentage.

==== Placeholders

The placeholders are a single character that can be associated with any of the configured sample. Bellow is an example
of a configuration file:

[source,yaml]
----
placeholders:
  "#": digit   <1>
  "%": letter  <2>

samples:
  letter:
    type: chars
    value: "abcdefghijklmnopqrstuvwxyz"
  digit:
    type: chars
    value: "0123456789"
----
<1> Associated with the `digit` sample
<2> Associated with the `letter` sample

=== Payload Template

Fake-O-Matic uses https://quarkus.io/guides/qute-reference[Qute] templates to produce the payloads. A couple of methods
can be used to get a fake data, the main one are:

random(sampleName)::
Gets a random sample from the given sample name.

number(min, max)::
Gets a random number that is at least `min` and less than `max`.

expression(placeholders)::
Gets a random data produced by replacing each placeholder by a random sample associated with it.

For more methods, check out the `FakeData` interface.

=== Utilities

You can use a couple of utilities for the template:

today(format)::
Gets the today date in the specified format as defined in the
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/SimpleDateFormat.html[SimpleDateFormat]
documentation.

env(name)::
Gets the named environment variable.

=== Configuration Properties

The following properties can be configured as a JVM argument (prefix `-D`), environment variable (with upper cases
and underscores), or a command line parameter:

endpoint.url|ENDPOINT_URL|--endpoint::
The endpoint that will receive the generated payloads. Fake-O-Matic will use the POST verb for calling it. Defaults to
`http://localhost:8080`.

endpoint.concurrency|ENDPOINT_CONCURRENCY|--concurrency::
The maximum number of concurrent requests to the endpoint. Defaults to `5`.

endpoint.insecure|ENDPOINT_INSECURE|--insecure::
Marks the endpoint as insecure or not. An insecure endpoint will not have its certificate check. Defaults to `false`.

generator.total|GENERATOR_TOTAL|--total::
The number of generated payloads. Defaults to `10`.

generator.configs|GENERATOR_CONFIGS|--configs::
Which configuration files should be used. Fake-O-Matic allows you to define parent configurations, so you can reuse them
in the way it suits you better. The configurations should be comma separated. The built-in configuration can be
included with a simple `fakeomatic` name. Fake-O-Matic will always follow the configuration order, so the first one
takes precedence. The built-in configuration can be found at `src/main/resources/META-INF/config/fakeomatic.yaml`.

generator.seed|GENERATOR_SEED|--seed::
The seed to use for the random functions. Fake-O-Matic will generate one if empty.

generator.buffer|GENERATOR_BUFFER|--buffer::
How many payloads should be buffered while we have ongoing requests. Defaults to `10`.

template.path|TEMPLATE_PATH|--template::
Where to locate the template for generating the payloads. Defaults to `./payload.json`.

template.type|TEMPLATE_TYPE|--template-type::
Which `Content-Type` to pass to the endpoint. Defaults to `application/json; charset=UTF-8`.

template.charset|TEMPLATE_CHARSET|--template-charset::
Which encode to use for loading the template file. Defaults to `UTF-8`.

== Example

The following examples can be used with the built-in configuration.

[source,json]
----
{
  "id": "{random('uuid')}",
  "message": "{random('cause')}",
  "device": "{expression('%%-#####')}"
}
----
