= Fake-O-Matic

Fake-O-Matic is a utility tool for creating and sending fake payloads to endpoints in order to test throughput.
On each iteration, Fake-O-Matic will generate a payload based on a provided template and a set of rules for generating
fake data.

== How to Build

Fake-O-Matic is build with https://quarkus.io[Quarkus] and supports native compilation. THe build is a good and old
`mvn package` command. If you wish to build a native binary, just activate the `native` profile
(`mvn -P native package`).

It's also possible to build Fake-O-Matic using https://github.com/openshift/source-to-image[source-to-image]:

[source,shell script]
----
s2i build . quay.io/quarkus/ubi-quarkus-native-s2i:19.3.2-java11 backpackcloud/fakeomatic
----

Fake-O-Matic is also published at https://quay.io/backpackcloud/fakeomatic[Quay.io] and the library is pushed to the
https://repo1.maven.org/maven/[Central Maven Repo] under the following properties:

groupId::
io.backpackcloud
artifactId::
fakeomatic
version::
0.7.0

== How to Configure

Fake-O-Matic expects you to define both data and template to generate the payloads. An optional seed can also be given
for reproducibility.

=== Data Generation

The rules for generating data can contain `samples` and `placeholders`. Samples are a set of data that Fake-O-Matic can
randomly pick and placeholders are characters that can be associated with the samples for to allow the use of
expressions for generating data.

[#configuration]
==== Configuration Values

Some configuration values can be externalized by different ways additionally to the normal String value:

env::
Fetches the value from an _Environment Variable_.

[source,yaml]
----
param:
  env: PARAM # reads the value from the PARAM environment variable (export PARAM=foo)
----

property::
Fetches the value from a _System Property_.

[source,yaml]
----
param:
  property: my.parameter # reads the value from the my.parameter system property (-Dmy.parameter=foo)
----

file::
Reads the value from a `file`.

[source,yaml]
----
param:
  file: /tmp/myfile # reads the value from the /tmp/myfile content
----

resource::
Reads the value using a `class.getResourceAsStream`.

[source,yaml]
----
param:
  resource: /com/example/configuration.yaml # reads the value from the configuration.yaml
                                            # file inside the com.example package
----

default::
Supplies a default value.

[source,yaml]
----
param:
  env: PARAM
  default: bar # uses "bar" as the value if the PARAM environment variable is not present
----

It is also possible to combine different approaches for getting the value by passing all the desired options.

[source,yaml]
----
param:
  env: PARAM
  property: my.parameter
  default: bar
----

The priority for getting the value is:

. `env`
. `property`
. `file`
. `resource`
. `defaultValue`

==== Samples

===== Characters

This sample can pick any character from a given string. Useful for defining a set of characters that can be used to
produce IDs or any other information that is not meant to be read.

====== Configuration

type::
`chars`

value::
String that holds the chars

====== Example

[source,yaml]
----
samples:
  letter:
    type: chars
    value: "abcdefghijklmnopqrstuvwxyz"
  digit:
    type: chars
    value: "0123456789"
----

===== List

This sample can pick any item from a given list of objects.

====== Configuration

type::
`list`

values::
List of raw values to use.

samples::
List of Samples to use.

location::
A <<configuration,configuration>> pointing to where to locate the list of values.

NOTE: You need to supply only one way of loading the values (`values`, `samples` or `location`).

====== Example

[source,yaml]
----
samples:
  cause:
    type: list
    values:
      - "clock speed"
      - "solar flares"
      - "electromagnetic radiation from satellite debris"
      - "static from nylon underwear"
      - "static from plastic slide rules"
      - "global warming"
      - "poor power conditioning"
      - "static buildup"
      - "doppler effect"
  first_name:
    type: list
    samples:
      - man_name
      - woman_name
  story:
    type: list
    location:
      env: STORIES
      property: stories
      default: stories.txt
----

===== API

This sample actually calls a given API to get data to use every time it's asked for a data.

====== Configuration

type::
`api`

url::
A <<configuration,configuration>> value defining the API endpoint.

return::
An optional https://tools.ietf.org/html/rfc6901[JSON Pointer] to specify which part of the API response represents the
data (uses the whole response if not supplied). The return is a `JsonNode`.

method::
Which HTTP method to use (defaults to `GET`).

payload::
An optional payload object to use for calling the API. Useful for `POST` requests.

template:::
A <<configuration,configuration>> defining which template to use

type:::
The content type of the template (defaults to `application/json`).

insecure::
Defines if the certificates should be trusted without checking (defaults to `false`).

options::
Any additional option to pass to the webclient (see `io.vertx.ext.web.client.WebClientOptions` docs).

path_vars::
A `string,string` map containing all the samples that forms the path on the uri (example: `/api/{uuid}` will be
replaced by the value from the sample `uuid`).

WARN: Due to the nature of this sample, it's not possible to reproduce the same payloads without relying on the
dependent API.

====== Example

[source,yaml]
----
samples:
  chuck_norris:
    type: api
    url: https://api.chucknorris.io/jokes/random
    return: /value
----

===== Universally Unique Identifier

This sample will produce a https://en.wikipedia.org/wiki/Universally_unique_identifier[universally unique identifier].

====== Configuration

type::
`uuid`

====== Example

[source,yaml]
----
samples:
  uuid:
    type: uuid
----

===== Composite

This sample will gather other samples and join them into one data.

====== Configuration

type::
`composite`

samples::
Which samples to join

separator::
Which separator to use (defaults to an empty string).

====== Example

[source,yaml]
----
samples:
  full_name:
    type: composite
    separator: " "
    samples:
      - first_name
      - last_name
----

===== Weight

A sample that allows you to define specific weights to each element.

====== Configuration

type::
`weight`

values::
The list of values.

weight:::
The weight of the value.

value:::
The value to use.

sample:::
The sample to use as a value.

====== Example

[source,yaml]
----
samples:
  color:
    type: weight
    values:
      - weight: 30
        value: blue
      - weight: 45
        value: yellow
      - weight: 10
        value: red
      - weight: 20
        value: brown
      - weight: 25
        value: cyan
----

NOTE: The sum of the weights don't necessary need to be `100`, but using a total weight of `100` helps to see the
weights as percentage.

===== Range

This sample generates numbers from a given interval.

====== Configuration

type::
`range`

min::
The minimum value.

max::
The maximum value.

====== Example

[source,yaml]
----
samples:
  grade:
    type: range
    min: 0
    max: 10
  temperature:
    type: range
    min: -10
    max: 20
----

===== Expression

A sample that generates data based on expressions.

====== Configuration

type::
`expression`

sample::
The sample to use as an expression.

expression::
The expression to use.

NOTE: You need to supply a `sample` or an `expression`.

====== Example

[source,yaml]
----
samples:
  address_expression:
    type: list
    values:
      - "Some Street ##"
      - "Another Street ###"
      - "Galaxy ###"
  address:
    type: expression
    sample: address_expression
  credit_card:
    type: expression
    expression: "################"
----

===== Template

A sample that can produce data based on external templates.

====== Configuration

type::
`template`

template::
A <<configuration,configuration>> pointing to where the template is.

====== Example

[source,yaml]
----
samples:
  address:
    type: template
    location:
      env: ADDRESS_TEMPLATE
      default: /usr/share/templates/address.json
----

===== Date

A sample that can generate dates based on a given interval.

====== Configuration

type::
`date`

from::
Defines the start date.

to::
Defines the end date.

period::
Defines a period instead of an end date. See the docs for `java.time.Period#parse`.

format::
The format to parse the supplied dates. Defaults to `dd-MM-yyyy`. See the docs for
`java.time.format.DateTimeFormatter#ofPatter`.

inclusive::
Sets if the end date is part of the interval or not.

NOTE: It is possible to use `today`, `yesterday` or `tomorrow` instead of the actual date values.

====== Example

[source,yaml]
----
samples:
  day_in_2020:
    type: date
    from: 2020-01-01
    to: 2021-01-01
  day_in_quarter:
    type: date
    from: 2020-01-01
    period: P3M
  yesterday_to_tomorrow:
    type: date
    from: yesterday
    to: tomorrow
    inclusive: true
----

===== Cache

A sample that caches the value. Useful when used with an API sample that posts data in order to create a data
dependency.

====== Configuration

type::
`cache`

sample::
The sample that should be cached.

ttl::
How many hits the value should last until the cache gets another one.

====== Example

[source,yaml]
----
samples:
  new_person:
    type: api
    url: http://api.example.com/persons
    method: POST
    payload:
      template: person.json
    return: /id
  person:
    type: cache
    sample: new_person
----

==== Placeholders

The placeholders are a single character that can be associated with any of the configured sample. Bellow is an example
of a configuration file:

[source,yaml]
----
placeholders:
  "#": digit   <1>
  "%": letter  <2>

samples:
  letter:
    type: chars
    value: "abcdefghijklmnopqrstuvwxyz"
  digit:
    type: chars
    value: "0123456789"
----
<1> Associated with the `digit` sample
<2> Associated with the `letter` sample

=== Payload Template

Fake-O-Matic uses https://quarkus.io/guides/qute-reference[Qute] templates to produce the payloads. A couple of methods
can be used to get a fake data, the main one are:

some(sampleName)::
Gets a random sample from the given sample name.

expression(placeholders)::
Gets a random data produced by replacing each placeholder by a random sample associated with it.

oneOf(values...)::
Randomly picks one of the given values using the internal `Random` reference.

For more methods, check out the `FakeData` interface.

=== Configuration Properties

The following properties can be configured as a JVM argument (prefix `-D`), environment variable (with upper cases
and underscores), or a command line parameter:

endpoint.url|ENDPOINT_URL|--endpoint::
The endpoint that will receive the generated payloads. Fake-O-Matic will use the POST verb for calling it. Defaults to
`http://localhost:8080`.

endpoint.concurrency|ENDPOINT_CONCURRENCY|--concurrency::
The maximum number of concurrent requests to the endpoint. Defaults to `5`.

endpoint.insecure|ENDPOINT_INSECURE|--insecure::
Marks the endpoint as insecure or not. An insecure endpoint will not have its certificate check. Defaults to `false`.

generator.total|GENERATOR_TOTAL|--total::
The number of generated payloads. Defaults to `10`.

generator.configs|GENERATOR_CONFIGS|--configs::
Which configuration files should be used. Fake-O-Matic allows you to define parent configurations, so you can reuse them
in the way it suits you better. The configurations should be comma separated. The built-in configuration can be
included with a simple `fakeomatic` name. Fake-O-Matic will always follow the configuration order, so the first one
takes precedence. The built-in configuration can be found at `src/main/resources/META-INF/config/fakeomatic.yaml`.

generator.seed|GENERATOR_SEED|--seed::
The seed to use for the random functions. Fake-O-Matic will generate one if empty.

generator.buffer|GENERATOR_BUFFER|--buffer::
How many payloads should be buffered while we have ongoing requests. Defaults to `10`.

template.path|TEMPLATE_PATH|--template::
Where to locate the template for generating the payloads. Defaults to `./payload.json`.

template.type|TEMPLATE_TYPE|--template-type::
Which `Content-Type` to pass to the endpoint. Defaults to `application/json`.

events.log.level|EVENTS_LOG_LEVEL|--events-log-level::
Sets the log level for the events. To see all the payloads and responses, set the log level to DEBUG.

== Example

The following examples can be used with the built-in configuration.

[source,json]
----
{
  "id": "{fake('uuid')}",
  "cause": "{fake('cause')}",
  "device": "{expression('%%-#####')}",
  "when": "{today('yyyy-MM-dd HH.mm.ss Z')}"
}
----

[source,json]
----
{
  "level": "{oneOf('INFO', 'WARN', 'ERROR')}",
  "message": "{fake('cause')}"
}
----