#
# The MIT License (MIT)
#
# Copyright (c) 2020 Marcelo Guimarães <ataxexe@backpackcloud.com>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

placeholders:
  "#": digit
  "%": downcase-letter
  "@": lowercase-char
  "^": uppercase-letter
  "$": uppercase-char
  "*": character

samples:
  uuid:
    type: uuid

  downcase-letter:
    type: chars
    value: "abcdefghijklmnopqrstuvwxyz"

  uppercase-letter:
    type: chars
    value: "ABCDEFGHIJKLMNOPQRSTUVWXYZ"

  digit:
    type: chars
    value: "0123456789"

  lowercase-char:
    type: list
    samples:
      - downcase-letter
      - digit

  uppercase-char:
    type: list
    samples:
      - uppercase-letter
      - digit

  character:
    type: list
    samples:
      - lowercase-letter
      - uppercase-letter
      - digit

  error-cause:
    type: list
    source:
      resource: META-INF/resources/config/causes.txt

  table-flip:
    type: list
    source:
      resource: META-INF/resources/config/table_flips.txt

  negative-adjective:
    type: list
    values:
      - stupid
      - crazy
      - damn
      - fucking
      - crappy
      - freaking

  positive-adjective:
    type: list
    values:
      - awesome
      - great
      - super
      - epic
      - smart
      - incredible
      - amazing

  adjective:
    type: list
    samples:
      - negative-adjective
      - positive-adjective

  negative-adverb:
    type: list
    values:
      - stupidly
      - crazily

  positive-adverb:
    type: list
    values:
      - intelligently
      - incredibly
      - smartly

  adverb:
    type: list
    samples:
      - negative-adverb
      - positive-adverb

  commit-message:
    type: template
    source:
      sample:
        type: list
        source:
          resource: META-INF/resources/config/commit_messages.txt

  chuck-norris:
    type: json
    source:
      sample:
        type: http
        url: https://api.chucknorris.io/jokes/random
    path: /value

  tronald-dump:
    type: json
    source:
      sample:
        type: http
        url: https://api.tronalddump.io/random/quote
        headers:
          Accept: application/json
    path: /value

  business-bullshit:
    type: json
    source:
      sample:
        type: http
        url: https://corporatebs-generator.sameerkumar.website
    path: /phrase

  whatthecommit:
    type: http
    url: http://whatthecommit.com/index.txt